### ISSUE TITLE
Create a dynamic stats meta image card for profile & advisory pages

### ISSUE THREAD

**Issue by benharvie** [418sec/huntr#1997]
- [x] Create a way for us to dynamically generate images (likely a lambda connected to an API Gateway)
- [x] Create a template image for advisories, show the details
- [x] Create a template image for a users profile, showing their details
- [x] Replace meta tags with URL to the dynamic image generator

**Comment by benharvie** [comment]
@adam-nygate could you reference the resource you had mentioned previously that could help us implement this feature?

Cheers x

**Comment by adam-nygate** [comment]
I don't recall a resource. Will update the ticket with further specs

**Comment by adam-nygate** [comment]
To see an example of this, post the following into discord:

`https://github.com/418sec/huntr`

**Comment by benharvie** [comment]
GitHub uses https://flayyer.com/, looking into the use of https://github.com/vercel/og-image as a free alternative.

Cheers x
