### ISSUE TITLE
Sponsoring open source

### ISSUE THREAD

**Issue by adam-nygate** [418sec/huntr#2080]
- [x] Explanation - 418sec/huntr-platform#1128
- [x] Prize pots - 418sec/huntr-platform#1130
- [x] Target finder - 418sec/huntr-platform#1129
